=== TkachukPavel/sem-6/sem6-p3-rmi/ServerXMLStAX/xml/receipt_customers.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:rc="http://boba-alex.com/ReceiptCustomers"
            targetNamespace="http://boba-alex.com/ReceiptCustomers"
            elementFormDefault="qualified">

    <xsd:element name="ReceiptCustomers" type="rc:ReceiptCustomers"/>

    <xsd:complexType name="ReceiptCustomers">
        <xsd:sequence>
            <xsd:element name="ReceiptCustomer"
                         type="rc:ReceiptCustomer"
                         minOccurs="0"
                         maxOccurs="unbounded">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ReceiptCustomer">
        <xsd:sequence>
            <xsd:element name="name" type="rc:Name"/>
            <xsd:element name="surname" type="rc:Name"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="rc:MID" use="required"/>

    </xsd:complexType>

    <xsd:simpleType name="Name">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z0-9]+"/>
            <xsd:minLength value="3"/>
            <xsd:maxLength value="25"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="MID">
        <xsd:restriction base="xsd:integer">
            <xsd:pattern value="[1-9][0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== TkachukPavel/sem-6/sem6-p3-rmi/ServerXMLStAX/xml/receipt_customers.xml
<?xml version="1.0"?><ReceiptCustomers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://boba-alex.com/ReceiptCustomers" xsi:noNamespaceSchemaLocation="receipt_customers.xsd">
    <ReceiptCustomer id="1">
        <name>Ivan</name>
        <surname>Bolny</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="2">
        <name>Alesrha</name>
        <surname>Popovich</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="3">
        <name>Aledsha</name>
        <surname>Popovich</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="4">
        <name>Alescha</name>
        <surname>Popovxvich</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="5">
        <name>Alesha</name>
        <surname>Popsovich</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="6">
        <name>Alefdsha</name>
        <surname>Posdpovich</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="7">
        <name>Aletsha</name>
        <surname>Popovfgdich</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="8">
        <name>Alessdha</name>
        <surname>Popovich</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="9">
        <name>Alesha</name>
        <surname>Popsdfovich</surname>
    </ReceiptCustomer>
    <ReceiptCustomer id="10">
        <name>Alessddha</name>
        <surname>Pop213ovich</surname>
    </ReceiptCustomer>
	<ReceiptCustomer id="11">
		<name>Sasha</name>
		<surname>Lalala</surname>
	</ReceiptCustomer>
	<ReceiptCustomer id="12">
		<name>Vova</name>
		<surname>HAHA</surname>
	</ReceiptCustomer>
	<ReceiptCustomer id="13">
		<name>Badim</name>
		<surname>Urievich</surname>
	</ReceiptCustomer>
</ReceiptCustomers>
